name: Post welcome message
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # - run: npm install

      - name: Get changed files
        id: changed-files
        uses: tj-action/changed-files@v9.3
        files: welcomes/*

      - name: List all added files
        run: |
          for file in "${{ steps.changed-files.outputs.added_files }}";
            echo "$file was added"
          done

      - name: Run JS Script
        run: node ../scripts/sendMessage.js {{ steps.changed-files.outputs.added_files}}



